# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://fehub.net
date_format: "ordinal"
title: FEHub
subtitle: "Find & Explore"
description: ""
keywords: FEHub
timezone: Asia/Shanghai
encoding: "utf-8"
repository: iamjichao/iamjichao.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: false
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: true
        hide-platforms: qq,qzone
    # 不蒜子访问统计 http://busuanzi.ibruce.info/
    busuanzi:
        enabled: true
        start_date: 2020-01-01
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: true
        image_alt: FEHub
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Ji Chao
organization: 
organization_url: 
github_username: iamjichao
location: Shanghai
email: iamjichao@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: iamjichao
    repo: blog-comments
    oauth:
        client_id: 5a841e8a87b06d346f3d
        client_secret: e0f22a1087ecec4dc50679f89f726b79e76bb628
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: iamjichao
    repo: blog-comments
    clientID: 5a841e8a87b06d346f3d
    clientSecret: e0f22a1087ecec4dc50679f89f726b79e76bb628
# https://utteranc.es/
utterances:
    repo: iamjichao/blog-comments
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
# google:
#     analytics_id: UA-80669434-1
#     adsense:
#         footer: true
#         sidebar: true 
#         sidebar-detail: true 
#         content_header: false
#         content_footer: false
